import pickle
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression

# 🧠 Sample training data (you can expand later)
texts = [
    "This assignment explains the results clearly in my own understanding",
    "The experiment was conducted and results were analyzed carefully",
    "I observed that the results changed due to temperature variations",
    "This response was generated using artificial intelligence tools",
    "The answer is automatically created by an AI system like ChatGPT",
    "This text appears structured and generated by an AI model"
]

# Labels: 0 = Human, 1 = AI
labels = [0, 0, 0, 1, 1, 1]

# 🔢 Convert text into numbers
vectorizer = TfidfVectorizer()
X = vectorizer.fit_transform(texts)

# 🤖 Train model
model = LogisticRegression()
model.fit(X, labels)

# 💾 Save model and vectorizer
pickle.dump(model, open("model/ai_model.pkl", "wb"))
pickle.dump(vectorizer, open("model/vectorizer.pkl", "wb"))

print("Model trained successfully!")